---
- name: Deploy Microservices using Helmfile in EKS
  hosts: localhost
  gather_facts: no
  tasks:

    - name: Ensure connection to EKS cluster
      kubernetes.core.k8s_cluster_info:
        name: micsvc-eks-cluster
      register: eks_info

    - name: Create micsvc namespace if it doesn't exist
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: micsvc
        state: present

    - name: Deploy Microservices using Helmfile
      kubernetes.core.k8s_apply:
        definition: "{{ lookup('file', '../micsvc-manifests/helmfile.yaml') }}"
      register: helmfile_apply_result

    - name: Display Helmfile Microservices deployment output
      ansible.builtin.debug:
        var: helmfile_apply_result

    - name: Verify microservices are running
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        namespace: micsvc
      register: pods_status

    - name: Display running microservices status
      ansible.builtin.debug:
        var: pods_status.resources

    - name: Verify services in namespace
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Service
        namespace: micsvc
      register: services_status

    - name: Display services in namespace status
      ansible.builtin.debug:
        var: services_status.resources